-- Lot -> Position: (CUSTODIAN_ID, ACCOUNT_NUMBER, SECURITY_ID, AS_OF_DATE) must exist in POSITION. Returns rows with no match.
SELECT e."CUSTODIAN_ID", e."ACCOUNT_NUMBER", e."SECURITY_ID", e."LOT_ID", e."AS_OF_DATE"
FROM {{ DATABASE }}."SILVER"."LOT" AS e
LEFT JOIN {{ DATABASE }}."SILVER"."POSITION" AS r ON r."CUSTODIAN_ID" = e."CUSTODIAN_ID" AND r."ACCOUNT_NUMBER" = e."ACCOUNT_NUMBER" AND r."SECURITY_ID" = e."SECURITY_ID" AND r."AS_OF_DATE" = e."AS_OF_DATE"
WHERE r."CUSTODIAN_ID" IS NULL;
