-- One finding per check, account, security or currency and balance type, custodian and business date. Returns those with more than one.
SELECT "CHECK_NAME", "CUSTODIAN_ID", "ACCOUNT_NUMBER", COALESCE("SECURITY_ID", '') AS "SECURITY_ID", COALESCE("CURRENCY", '') AS "CURRENCY", COALESCE("BALANCE_TYPE", '') AS "BALANCE_TYPE", "AS_OF_DATE", COUNT(*) AS ROW_COUNT
FROM {{ DATABASE }}."CONTROL"."RECONCILIATION_BREAKS"
GROUP BY "CHECK_NAME", "CUSTODIAN_ID", "ACCOUNT_NUMBER", COALESCE("SECURITY_ID", ''), COALESCE("CURRENCY", ''), COALESCE("BALANCE_TYPE", ''), "AS_OF_DATE"
HAVING COUNT(*) > 1;
