-- Reconcile one custodian's business date: the position identity (prior snapshot + the transactions since = this snapshot) and
-- each cash balance identity (SETTLED, TRADE_DATE), with the tolerance per field type the pack declares. What it finds
-- replaces what an earlier run found for the same custodian and date, in one transaction, so a break that was fixed is gone; the run and its
-- row counts are logged. Rendered by astra-data reconciliation render.
CREATE OR REPLACE PROCEDURE {{ DATABASE }}."CONTROL"."RECONCILE"("CUSTODIAN_ID" STRING, "AS_OF_DATE" DATE)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
COMMENT = 'Reconciles the positions and cash balances of a custodian and business date against the transactions between snapshots. Rendered by astra-data reconciliation render.'
AS
$$
DECLARE
  run_id STRING DEFAULT UUID_STRING();
  started_at TIMESTAMP_NTZ(6) DEFAULT SYSDATE();
  positions INTEGER DEFAULT 0;
  balances INTEGER DEFAULT 0;
  found INTEGER DEFAULT 0;
BEGIN
  positions := (SELECT COUNT(*) FROM {{ DATABASE }}."SILVER"."POSITION" WHERE "CUSTODIAN_ID" = :CUSTODIAN_ID AND "AS_OF_DATE" = :AS_OF_DATE);
  balances := (SELECT COUNT(*) FROM {{ DATABASE }}."SILVER"."CASH_BALANCE" WHERE "CUSTODIAN_ID" = :CUSTODIAN_ID AND "AS_OF_DATE" = :AS_OF_DATE);

  BEGIN TRANSACTION;
  DELETE FROM {{ DATABASE }}."CONTROL"."RECONCILIATION_BREAKS" WHERE "CUSTODIAN_ID" = :CUSTODIAN_ID AND "AS_OF_DATE" = :AS_OF_DATE;
  INSERT INTO {{ DATABASE }}."CONTROL"."RECONCILIATION_BREAKS" ("RUN_ID", "CHECK_NAME", "CATEGORY", "CUSTODIAN_ID", "ACCOUNT_NUMBER", "SECURITY_ID", "CURRENCY", "BALANCE_TYPE", "AS_OF_DATE", "PRIOR_DATE", "PRIOR_VALUE", "MOVEMENT", "EXPECTED", "ACTUAL", "DIFFERENCE", "UNVERIFIABLE_COUNT", "REJECTION_CODE", "DETECTED_AT")
  SELECT :run_id, b."CHECK_NAME", b."CATEGORY", b."CUSTODIAN_ID", b."ACCOUNT_NUMBER", b."SECURITY_ID", b."CURRENCY", b."BALANCE_TYPE", b."AS_OF_DATE", b."PRIOR_DATE", b."PRIOR_VALUE", b."MOVEMENT", b."EXPECTED", b."ACTUAL", b."DIFFERENCE", b."UNVERIFIABLE_COUNT", b."REJECTION_CODE", SYSDATE()
  FROM (
    SELECT * FROM (
    WITH "PRIOR_DATES" AS (
      SELECT "ACCOUNT_NUMBER", MAX("AS_OF_DATE") AS "PRIOR_DATE"
      FROM {{ DATABASE }}."SILVER"."POSITION"
      WHERE "CUSTODIAN_ID" = :CUSTODIAN_ID AND "AS_OF_DATE" < :AS_OF_DATE
      GROUP BY "ACCOUNT_NUMBER"
    ), "PRIOR_ROWS" AS (
      SELECT p."ACCOUNT_NUMBER", p."SECURITY_ID", p."QUANTITY"
      FROM {{ DATABASE }}."SILVER"."POSITION" p
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = p."ACCOUNT_NUMBER" AND d."PRIOR_DATE" = p."AS_OF_DATE"
      WHERE p."CUSTODIAN_ID" = :CUSTODIAN_ID
    ), "CURRENT_ROWS" AS (
      SELECT p."ACCOUNT_NUMBER", p."SECURITY_ID", p."QUANTITY"
      FROM {{ DATABASE }}."SILVER"."POSITION" p
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = p."ACCOUNT_NUMBER"
      WHERE p."CUSTODIAN_ID" = :CUSTODIAN_ID AND p."AS_OF_DATE" = :AS_OF_DATE
    ), "MOVES" AS (
      SELECT t."ACCOUNT_NUMBER", t."SECURITY_ID",
             SUM(CASE WHEN (t."TRADE_DATE" > d."PRIOR_DATE" AND t."TRADE_DATE" <= :AS_OF_DATE) AND m."FACTOR" IN (1, -1) AND t."QUANTITY" IS NOT NULL THEN m."FACTOR" * ABS(t."QUANTITY") ELSE 0 END) AS "MOVEMENT",
             SUM(CASE WHEN m."TYPE" IS NULL OR m."UNRECONCILABLE" OR t."QUANTITY" IS NULL THEN 1 ELSE 0 END) AS "UNVERIFIABLE"
      FROM {{ DATABASE }}."SILVER"."TRANSACTION" t
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = t."ACCOUNT_NUMBER"
      LEFT JOIN (SELECT * FROM VALUES ('BUY', 1, FALSE), ('SELL', -1, FALSE), ('TRANSFER_IN', 1, FALSE), ('TRANSFER_OUT', -1, FALSE), ('DIVIDEND', 0, FALSE), ('INTEREST', 0, FALSE), ('CAPITAL_GAIN', 0, FALSE), ('FEE', 0, FALSE), ('DEPOSIT', 0, FALSE), ('WITHDRAWAL', 0, FALSE), ('CORPORATE_ACTION', 0, TRUE), ('ADJUSTMENT', 0, TRUE), ('OTHER', 0, TRUE) AS v ("TYPE", "FACTOR", "UNRECONCILABLE")) m ON m."TYPE" = t."TRANSACTION_TYPE"
      WHERE t."CUSTODIAN_ID" = :CUSTODIAN_ID AND t."STATUS" = 'ACTIVE' AND t."SECURITY_ID" IS NOT NULL
        AND (m."TYPE" IS NULL OR m."UNRECONCILABLE" OR m."FACTOR" <> 0)
        AND (t."TRADE_DATE" > d."PRIOR_DATE" AND t."TRADE_DATE" <= :AS_OF_DATE)
      GROUP BY t."ACCOUNT_NUMBER", t."SECURITY_ID"
    ), "KEYS" AS (
      SELECT "ACCOUNT_NUMBER", "SECURITY_ID" FROM "PRIOR_ROWS"
      UNION SELECT "ACCOUNT_NUMBER", "SECURITY_ID" FROM "CURRENT_ROWS"
      UNION SELECT "ACCOUNT_NUMBER", "SECURITY_ID" FROM "MOVES"
    ), "EVAL" AS (
      SELECT k."ACCOUNT_NUMBER", k."SECURITY_ID", d."PRIOR_DATE", pr."QUANTITY" AS "PRIOR_VALUE", cu."QUANTITY" AS "ACTUAL",
             COALESCE(mv."MOVEMENT", 0) AS "MOVEMENT", COALESCE(mv."UNVERIFIABLE", 0) AS "UNVERIFIABLE_COUNT",
             COALESCE(pr."QUANTITY", 0) + COALESCE(mv."MOVEMENT", 0) AS "EXPECTED"
      FROM "KEYS" k
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = k."ACCOUNT_NUMBER"
      LEFT JOIN "PRIOR_ROWS" pr ON pr."ACCOUNT_NUMBER" = k."ACCOUNT_NUMBER" AND pr."SECURITY_ID" = k."SECURITY_ID"
      LEFT JOIN "CURRENT_ROWS" cu ON cu."ACCOUNT_NUMBER" = k."ACCOUNT_NUMBER" AND cu."SECURITY_ID" = k."SECURITY_ID"
      LEFT JOIN "MOVES" mv ON mv."ACCOUNT_NUMBER" = k."ACCOUNT_NUMBER" AND mv."SECURITY_ID" = k."SECURITY_ID"
    )
    SELECT 'position_quantity' AS "CHECK_NAME",
           CASE WHEN "UNVERIFIABLE_COUNT" > 0 THEN 'unverifiable' WHEN "ACTUAL" IS NULL THEN 'disappeared' WHEN "PRIOR_VALUE" IS NULL THEN 'appeared' ELSE 'mismatch' END AS "CATEGORY",
           :CUSTODIAN_ID AS "CUSTODIAN_ID", "ACCOUNT_NUMBER", "SECURITY_ID", CAST(NULL AS STRING) AS "CURRENCY", CAST(NULL AS STRING) AS "BALANCE_TYPE",
           :AS_OF_DATE AS "AS_OF_DATE", "PRIOR_DATE", "PRIOR_VALUE", "MOVEMENT", "EXPECTED", "ACTUAL",
           COALESCE("ACTUAL", 0) - "EXPECTED" AS "DIFFERENCE", "UNVERIFIABLE_COUNT", 'POSITION_QUANTITY_MISMATCH' AS "REJECTION_CODE"
    FROM "EVAL"
    WHERE "UNVERIFIABLE_COUNT" > 0 OR NOT ("EXPECTED" = COALESCE("ACTUAL", 0))
    )
    UNION ALL
    SELECT * FROM (
    WITH "PRIOR_DATES" AS (
      SELECT "ACCOUNT_NUMBER", "CURRENCY", MAX("AS_OF_DATE") AS "PRIOR_DATE"
      FROM {{ DATABASE }}."SILVER"."CASH_BALANCE"
      WHERE "CUSTODIAN_ID" = :CUSTODIAN_ID AND "BALANCE_TYPE" = 'SETTLED' AND "AS_OF_DATE" < :AS_OF_DATE
      GROUP BY "ACCOUNT_NUMBER", "CURRENCY"
    ), "PRIOR_ROWS" AS (
      SELECT b."ACCOUNT_NUMBER", b."CURRENCY", b."AMOUNT"
      FROM {{ DATABASE }}."SILVER"."CASH_BALANCE" b
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = b."ACCOUNT_NUMBER" AND d."CURRENCY" = b."CURRENCY" AND d."PRIOR_DATE" = b."AS_OF_DATE"
      WHERE b."CUSTODIAN_ID" = :CUSTODIAN_ID AND b."BALANCE_TYPE" = 'SETTLED'
    ), "CURRENT_ROWS" AS (
      SELECT b."ACCOUNT_NUMBER", b."CURRENCY", b."AMOUNT"
      FROM {{ DATABASE }}."SILVER"."CASH_BALANCE" b
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = b."ACCOUNT_NUMBER" AND d."CURRENCY" = b."CURRENCY"
      WHERE b."CUSTODIAN_ID" = :CUSTODIAN_ID AND b."BALANCE_TYPE" = 'SETTLED' AND b."AS_OF_DATE" = :AS_OF_DATE
    ), "MOVES" AS (
      SELECT t."ACCOUNT_NUMBER", t."CURRENCY",
             SUM(CASE WHEN (t."SETTLE_DATE" > d."PRIOR_DATE" AND t."SETTLE_DATE" <= :AS_OF_DATE) THEN t."NET_AMOUNT" ELSE 0 END) AS "MOVEMENT",
             SUM(CASE WHEN (t."SETTLE_DATE" IS NULL AND t."TRADE_DATE" > d."PRIOR_DATE" AND t."TRADE_DATE" <= :AS_OF_DATE) THEN 1 ELSE 0 END) AS "UNVERIFIABLE"
      FROM {{ DATABASE }}."SILVER"."TRANSACTION" t
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = t."ACCOUNT_NUMBER" AND d."CURRENCY" = t."CURRENCY"
      WHERE t."CUSTODIAN_ID" = :CUSTODIAN_ID AND t."STATUS" = 'ACTIVE' AND ((t."SETTLE_DATE" > d."PRIOR_DATE" AND t."SETTLE_DATE" <= :AS_OF_DATE) OR (t."SETTLE_DATE" IS NULL AND t."TRADE_DATE" > d."PRIOR_DATE" AND t."TRADE_DATE" <= :AS_OF_DATE))
      GROUP BY t."ACCOUNT_NUMBER", t."CURRENCY"
    ), "EVAL" AS (
      SELECT d."ACCOUNT_NUMBER", d."CURRENCY", d."PRIOR_DATE", pr."AMOUNT" AS "PRIOR_VALUE", cu."AMOUNT" AS "ACTUAL",
             COALESCE(mv."MOVEMENT", 0) AS "MOVEMENT", COALESCE(mv."UNVERIFIABLE", 0) AS "UNVERIFIABLE_COUNT",
             pr."AMOUNT" + COALESCE(mv."MOVEMENT", 0) AS "EXPECTED"
      FROM "PRIOR_DATES" d
      JOIN "PRIOR_ROWS" pr ON pr."ACCOUNT_NUMBER" = d."ACCOUNT_NUMBER" AND pr."CURRENCY" = d."CURRENCY"
      LEFT JOIN "CURRENT_ROWS" cu ON cu."ACCOUNT_NUMBER" = d."ACCOUNT_NUMBER" AND cu."CURRENCY" = d."CURRENCY"
      LEFT JOIN "MOVES" mv ON mv."ACCOUNT_NUMBER" = d."ACCOUNT_NUMBER" AND mv."CURRENCY" = d."CURRENCY"
    )
    SELECT 'cash_balance' AS "CHECK_NAME",
           CASE WHEN "UNVERIFIABLE_COUNT" > 0 THEN 'unverifiable' WHEN "ACTUAL" IS NULL THEN 'disappeared' ELSE 'mismatch' END AS "CATEGORY",
           :CUSTODIAN_ID AS "CUSTODIAN_ID", "ACCOUNT_NUMBER", CAST(NULL AS STRING) AS "SECURITY_ID", "CURRENCY", 'SETTLED' AS "BALANCE_TYPE",
           :AS_OF_DATE AS "AS_OF_DATE", "PRIOR_DATE", "PRIOR_VALUE", "MOVEMENT", "EXPECTED", "ACTUAL",
           COALESCE("ACTUAL", 0) - "EXPECTED" AS "DIFFERENCE", "UNVERIFIABLE_COUNT", 'CASH_BALANCE_MISMATCH' AS "REJECTION_CODE"
    FROM "EVAL"
    WHERE "UNVERIFIABLE_COUNT" > 0 OR NOT ("EXPECTED" = COALESCE("ACTUAL", 0))
    )
    UNION ALL
    SELECT * FROM (
    WITH "PRIOR_DATES" AS (
      SELECT "ACCOUNT_NUMBER", "CURRENCY", MAX("AS_OF_DATE") AS "PRIOR_DATE"
      FROM {{ DATABASE }}."SILVER"."CASH_BALANCE"
      WHERE "CUSTODIAN_ID" = :CUSTODIAN_ID AND "BALANCE_TYPE" = 'TRADE_DATE' AND "AS_OF_DATE" < :AS_OF_DATE
      GROUP BY "ACCOUNT_NUMBER", "CURRENCY"
    ), "PRIOR_ROWS" AS (
      SELECT b."ACCOUNT_NUMBER", b."CURRENCY", b."AMOUNT"
      FROM {{ DATABASE }}."SILVER"."CASH_BALANCE" b
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = b."ACCOUNT_NUMBER" AND d."CURRENCY" = b."CURRENCY" AND d."PRIOR_DATE" = b."AS_OF_DATE"
      WHERE b."CUSTODIAN_ID" = :CUSTODIAN_ID AND b."BALANCE_TYPE" = 'TRADE_DATE'
    ), "CURRENT_ROWS" AS (
      SELECT b."ACCOUNT_NUMBER", b."CURRENCY", b."AMOUNT"
      FROM {{ DATABASE }}."SILVER"."CASH_BALANCE" b
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = b."ACCOUNT_NUMBER" AND d."CURRENCY" = b."CURRENCY"
      WHERE b."CUSTODIAN_ID" = :CUSTODIAN_ID AND b."BALANCE_TYPE" = 'TRADE_DATE' AND b."AS_OF_DATE" = :AS_OF_DATE
    ), "MOVES" AS (
      SELECT t."ACCOUNT_NUMBER", t."CURRENCY",
             SUM(CASE WHEN (t."TRADE_DATE" > d."PRIOR_DATE" AND t."TRADE_DATE" <= :AS_OF_DATE) THEN t."NET_AMOUNT" ELSE 0 END) AS "MOVEMENT",
             CAST(0 AS INTEGER) AS "UNVERIFIABLE"
      FROM {{ DATABASE }}."SILVER"."TRANSACTION" t
      JOIN "PRIOR_DATES" d ON d."ACCOUNT_NUMBER" = t."ACCOUNT_NUMBER" AND d."CURRENCY" = t."CURRENCY"
      WHERE t."CUSTODIAN_ID" = :CUSTODIAN_ID AND t."STATUS" = 'ACTIVE' AND (t."TRADE_DATE" > d."PRIOR_DATE" AND t."TRADE_DATE" <= :AS_OF_DATE)
      GROUP BY t."ACCOUNT_NUMBER", t."CURRENCY"
    ), "EVAL" AS (
      SELECT d."ACCOUNT_NUMBER", d."CURRENCY", d."PRIOR_DATE", pr."AMOUNT" AS "PRIOR_VALUE", cu."AMOUNT" AS "ACTUAL",
             COALESCE(mv."MOVEMENT", 0) AS "MOVEMENT", COALESCE(mv."UNVERIFIABLE", 0) AS "UNVERIFIABLE_COUNT",
             pr."AMOUNT" + COALESCE(mv."MOVEMENT", 0) AS "EXPECTED"
      FROM "PRIOR_DATES" d
      JOIN "PRIOR_ROWS" pr ON pr."ACCOUNT_NUMBER" = d."ACCOUNT_NUMBER" AND pr."CURRENCY" = d."CURRENCY"
      LEFT JOIN "CURRENT_ROWS" cu ON cu."ACCOUNT_NUMBER" = d."ACCOUNT_NUMBER" AND cu."CURRENCY" = d."CURRENCY"
      LEFT JOIN "MOVES" mv ON mv."ACCOUNT_NUMBER" = d."ACCOUNT_NUMBER" AND mv."CURRENCY" = d."CURRENCY"
    )
    SELECT 'cash_balance' AS "CHECK_NAME",
           CASE WHEN "UNVERIFIABLE_COUNT" > 0 THEN 'unverifiable' WHEN "ACTUAL" IS NULL THEN 'disappeared' ELSE 'mismatch' END AS "CATEGORY",
           :CUSTODIAN_ID AS "CUSTODIAN_ID", "ACCOUNT_NUMBER", CAST(NULL AS STRING) AS "SECURITY_ID", "CURRENCY", 'TRADE_DATE' AS "BALANCE_TYPE",
           :AS_OF_DATE AS "AS_OF_DATE", "PRIOR_DATE", "PRIOR_VALUE", "MOVEMENT", "EXPECTED", "ACTUAL",
           COALESCE("ACTUAL", 0) - "EXPECTED" AS "DIFFERENCE", "UNVERIFIABLE_COUNT", 'CASH_BALANCE_MISMATCH' AS "REJECTION_CODE"
    FROM "EVAL"
    WHERE "UNVERIFIABLE_COUNT" > 0 OR NOT ("EXPECTED" = COALESCE("ACTUAL", 0))
    )
  ) b;
  found := SQLROWCOUNT;
  INSERT INTO {{ DATABASE }}."CONTROL"."RECONCILIATION_RUNS" ("RUN_ID", "CUSTODIAN_ID", "AS_OF_DATE", "STARTED_AT", "FINISHED_AT", "POSITIONS_IN_SCOPE", "BALANCES_IN_SCOPE", "BREAKS_FOUND")
  SELECT :run_id, :CUSTODIAN_ID, :AS_OF_DATE, :started_at, SYSDATE(), :positions, :balances, :found;
  COMMIT;
  RETURN found || ' break(s) for ' || CUSTODIAN_ID || ' on ' || TO_VARCHAR(AS_OF_DATE) || ' (run ' || run_id || ')';
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
$$;
