-- Resolution views: one row per identifier a custodian record may carry, so resolution is a single join
-- against the replica and never a call to the source system. Rendered by astra-data reference render.

-- Security master: identifiers tried in order CUSIP, ISIN, SEDOL, TICKER, OCC_SYMBOL; a value matching more than one key is SECURITY_AMBIGUOUS, none is SECURITY_NOT_FOUND.
CREATE OR REPLACE VIEW {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_IDENTIFIERS"
COMMENT = 'Alternate identifiers of SECURITY_MASTER unpivoted for resolution joins: CUSIP, ISIN, SEDOL, TICKER, OCC_SYMBOL.'
AS
SELECT "SECURITY_ID", 'CUSIP' AS IDENTIFIER_TYPE, "CUSIP" AS IDENTIFIER_VALUE, 1 AS PRIORITY FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" WHERE "CUSIP" IS NOT NULL
UNION ALL
SELECT "SECURITY_ID", 'ISIN' AS IDENTIFIER_TYPE, "ISIN" AS IDENTIFIER_VALUE, 2 AS PRIORITY FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" WHERE "ISIN" IS NOT NULL
UNION ALL
SELECT "SECURITY_ID", 'SEDOL' AS IDENTIFIER_TYPE, "SEDOL" AS IDENTIFIER_VALUE, 3 AS PRIORITY FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" WHERE "SEDOL" IS NOT NULL
UNION ALL
SELECT "SECURITY_ID", 'TICKER' AS IDENTIFIER_TYPE, "TICKER" AS IDENTIFIER_VALUE, 4 AS PRIORITY FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" WHERE "TICKER" IS NOT NULL
UNION ALL
SELECT "SECURITY_ID", 'OCC_SYMBOL' AS IDENTIFIER_TYPE, "OCC_SYMBOL" AS IDENTIFIER_VALUE, 5 AS PRIORITY FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" WHERE "OCC_SYMBOL" IS NOT NULL;

-- Account cross-reference: records resolve by the key (CUSTODIAN_ID, CUSTODIAN_ACCOUNT_NUMBER) directly against {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF".
