-- Security master (SOS): load the newest snapshot files, compute the delta against the replica,
-- bring the replica in line and record the run with its row counts. Rendered by astra-data reference render.
CREATE OR REPLACE PROCEDURE {{ DATABASE }}."REFERENCE"."REPLICATE_SECURITY_MASTER"(SNAPSHOT_DATE DATE)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
COMMENT = 'Replicates Security master from SOS snapshots under security_master/. Records every run in CONTROL.REFERENCE_DATA_RUNS and every change in SECURITY_MASTER_CHANGES.'
AS
$$
DECLARE
  run_id STRING DEFAULT UUID_STRING();
  started_at TIMESTAMP_NTZ DEFAULT SYSDATE();
  snapshot DATE DEFAULT COALESCE(:SNAPSHOT_DATE, CURRENT_DATE());
  files_loaded INTEGER DEFAULT 0;
  rows_source INTEGER DEFAULT 0;
  rows_conflict INTEGER DEFAULT 0;
  rows_inserted INTEGER DEFAULT 0;
  rows_updated INTEGER DEFAULT 0;
  rows_deleted INTEGER DEFAULT 0;
  rows_unchanged INTEGER DEFAULT 0;
  rows_total INTEGER DEFAULT 0;
BEGIN
  -- 1. The newest snapshot: files under the feed's folder that no earlier run has loaded.
  TRUNCATE TABLE {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING";
  COPY INTO {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING" ("SECURITY_ID", "CUSIP", "ISIN", "SEDOL", "TICKER", "DESCRIPTION", "ASSET_CLASS", "SECURITY_TYPE", "ISSUER", "CURRENCY", "PRICE_FACTOR", "MATURITY_DATE", "STATUS", "SOURCE_UPDATED_AT", "SOURCE_FILE", "SOURCE_ROW")
  FROM (SELECT $1::STRING, $2::STRING, $3::STRING, $4::STRING, $5::STRING, $6::STRING, $7::STRING, $8::STRING, $9::STRING, $10::STRING, $11::NUMBER(18,8), $12::DATE, $13::STRING, $14::TIMESTAMP_NTZ(6), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER FROM @{{ DATABASE }}."REFERENCE"."LANDING"/security_master/)
  FILE_FORMAT = (FORMAT_NAME = '{{ DATABASE }}.REFERENCE.CSV')
  PATTERN = '.*[.]csv'
  ON_ERROR = 'ABORT_STATEMENT';
  SELECT COUNT(*), COUNT(DISTINCT "SOURCE_FILE") INTO :rows_source, :files_loaded FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING";

  IF (files_loaded = 0) THEN
    INSERT INTO {{ DATABASE }}."CONTROL"."REFERENCE_DATA_RUNS" (RUN_ID, FEED_ID, DOMAIN, STARTED_AT, FINISHED_AT, STATUS, SNAPSHOT_DATE, FILES_LOADED, ROWS_SOURCE, ROWS_TOTAL)
    SELECT :run_id, 'security_master', 'custodial', :started_at, SYSDATE(), 'skipped', :snapshot, 0, 0, COUNT(*) FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER";
    RETURN 'skipped: no new snapshot files under security_master/';
  END IF;

  -- 2. Conflicts: keys blank or repeated in the snapshot stay out; the replica keeps what it had.
  INSERT INTO {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_CONFLICTS" (RUN_ID, "SECURITY_ID", ROW_COUNT, REJECTION_CODE)
  SELECT :run_id, "SECURITY_ID", COUNT(*), 'REFERENCE_DATA_CONFLICT'
  FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING"
  GROUP BY "SECURITY_ID"
  HAVING COUNT(*) > 1 OR NOT ("SECURITY_ID" IS NOT NULL);
  SELECT COALESCE(SUM(ROW_COUNT), 0) INTO :rows_conflict FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_CONFLICTS" WHERE RUN_ID = :run_id;

  -- 3. The delta: what the snapshot removes, adds and changes.
  INSERT INTO {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_CHANGES" (RUN_ID, CHANGED_AT, CHANGE, "SECURITY_ID", BEFORE, AFTER)
  SELECT :run_id, SYSDATE(), 'deleted', r."SECURITY_ID", OBJECT_CONSTRUCT_KEEP_NULL('SECURITY_ID', r."SECURITY_ID", 'CUSIP', r."CUSIP", 'ISIN', r."ISIN", 'SEDOL', r."SEDOL", 'TICKER', r."TICKER", 'DESCRIPTION', r."DESCRIPTION", 'ASSET_CLASS', r."ASSET_CLASS", 'SECURITY_TYPE', r."SECURITY_TYPE", 'ISSUER', r."ISSUER", 'CURRENCY', r."CURRENCY", 'PRICE_FACTOR', r."PRICE_FACTOR", 'MATURITY_DATE', r."MATURITY_DATE", 'STATUS', r."STATUS", 'SOURCE_UPDATED_AT', r."SOURCE_UPDATED_AT")::STRING, NULL
  FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" r
  WHERE NOT EXISTS (SELECT 1 FROM (SELECT "SECURITY_ID", "CUSIP", "ISIN", "SEDOL", "TICKER", "DESCRIPTION", "ASSET_CLASS", "SECURITY_TYPE", "ISSUER", "CURRENCY", "PRICE_FACTOR", "MATURITY_DATE", "STATUS", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING" WHERE "SECURITY_ID" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "SECURITY_ID") = 1) s WHERE r."SECURITY_ID" = s."SECURITY_ID")
    AND NOT EXISTS (SELECT 1 FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_CONFLICTS" c WHERE c.RUN_ID = :run_id AND c."SECURITY_ID" IS NOT DISTINCT FROM r."SECURITY_ID")
  UNION ALL
  SELECT :run_id, SYSDATE(), 'inserted', s."SECURITY_ID", NULL, OBJECT_CONSTRUCT_KEEP_NULL('SECURITY_ID', s."SECURITY_ID", 'CUSIP', s."CUSIP", 'ISIN', s."ISIN", 'SEDOL', s."SEDOL", 'TICKER', s."TICKER", 'DESCRIPTION', s."DESCRIPTION", 'ASSET_CLASS', s."ASSET_CLASS", 'SECURITY_TYPE', s."SECURITY_TYPE", 'ISSUER', s."ISSUER", 'CURRENCY', s."CURRENCY", 'PRICE_FACTOR', s."PRICE_FACTOR", 'MATURITY_DATE', s."MATURITY_DATE", 'STATUS', s."STATUS", 'SOURCE_UPDATED_AT', s."SOURCE_UPDATED_AT")::STRING
  FROM (SELECT "SECURITY_ID", "CUSIP", "ISIN", "SEDOL", "TICKER", "DESCRIPTION", "ASSET_CLASS", "SECURITY_TYPE", "ISSUER", "CURRENCY", "PRICE_FACTOR", "MATURITY_DATE", "STATUS", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING" WHERE "SECURITY_ID" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "SECURITY_ID") = 1) s
  WHERE NOT EXISTS (SELECT 1 FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" r WHERE r."SECURITY_ID" = s."SECURITY_ID")
  UNION ALL
  SELECT :run_id, SYSDATE(), 'updated', s."SECURITY_ID", OBJECT_CONSTRUCT_KEEP_NULL('SECURITY_ID', r."SECURITY_ID", 'CUSIP', r."CUSIP", 'ISIN', r."ISIN", 'SEDOL', r."SEDOL", 'TICKER', r."TICKER", 'DESCRIPTION', r."DESCRIPTION", 'ASSET_CLASS', r."ASSET_CLASS", 'SECURITY_TYPE', r."SECURITY_TYPE", 'ISSUER', r."ISSUER", 'CURRENCY', r."CURRENCY", 'PRICE_FACTOR', r."PRICE_FACTOR", 'MATURITY_DATE', r."MATURITY_DATE", 'STATUS', r."STATUS", 'SOURCE_UPDATED_AT', r."SOURCE_UPDATED_AT")::STRING, OBJECT_CONSTRUCT_KEEP_NULL('SECURITY_ID', s."SECURITY_ID", 'CUSIP', s."CUSIP", 'ISIN', s."ISIN", 'SEDOL', s."SEDOL", 'TICKER', s."TICKER", 'DESCRIPTION', s."DESCRIPTION", 'ASSET_CLASS', s."ASSET_CLASS", 'SECURITY_TYPE', s."SECURITY_TYPE", 'ISSUER', s."ISSUER", 'CURRENCY', s."CURRENCY", 'PRICE_FACTOR', s."PRICE_FACTOR", 'MATURITY_DATE', s."MATURITY_DATE", 'STATUS', s."STATUS", 'SOURCE_UPDATED_AT', s."SOURCE_UPDATED_AT")::STRING
  FROM (SELECT "SECURITY_ID", "CUSIP", "ISIN", "SEDOL", "TICKER", "DESCRIPTION", "ASSET_CLASS", "SECURITY_TYPE", "ISSUER", "CURRENCY", "PRICE_FACTOR", "MATURITY_DATE", "STATUS", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING" WHERE "SECURITY_ID" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "SECURITY_ID") = 1) s
  JOIN {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" r ON r."SECURITY_ID" = s."SECURITY_ID"
  WHERE s."CUSIP" IS DISTINCT FROM r."CUSIP" OR s."ISIN" IS DISTINCT FROM r."ISIN" OR s."SEDOL" IS DISTINCT FROM r."SEDOL" OR s."TICKER" IS DISTINCT FROM r."TICKER" OR s."DESCRIPTION" IS DISTINCT FROM r."DESCRIPTION" OR s."ASSET_CLASS" IS DISTINCT FROM r."ASSET_CLASS" OR s."SECURITY_TYPE" IS DISTINCT FROM r."SECURITY_TYPE" OR s."ISSUER" IS DISTINCT FROM r."ISSUER" OR s."CURRENCY" IS DISTINCT FROM r."CURRENCY" OR s."PRICE_FACTOR" IS DISTINCT FROM r."PRICE_FACTOR" OR s."MATURITY_DATE" IS DISTINCT FROM r."MATURITY_DATE" OR s."STATUS" IS DISTINCT FROM r."STATUS" OR s."SOURCE_UPDATED_AT" IS DISTINCT FROM r."SOURCE_UPDATED_AT";
  SELECT COUNT_IF(CHANGE = 'inserted'), COUNT_IF(CHANGE = 'updated'), COUNT_IF(CHANGE = 'deleted')
    INTO :rows_inserted, :rows_updated, :rows_deleted
  FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_CHANGES" WHERE RUN_ID = :run_id;

  -- 4. Bring the replica in line.
  DELETE FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" r
  WHERE EXISTS (SELECT 1 FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_CHANGES" c WHERE c.RUN_ID = :run_id AND c.CHANGE = 'deleted' AND c."SECURITY_ID" = r."SECURITY_ID");
  MERGE INTO {{ DATABASE }}."REFERENCE"."SECURITY_MASTER" r
  USING (SELECT "SECURITY_ID", "CUSIP", "ISIN", "SEDOL", "TICKER", "DESCRIPTION", "ASSET_CLASS", "SECURITY_TYPE", "ISSUER", "CURRENCY", "PRICE_FACTOR", "MATURITY_DATE", "STATUS", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER_STAGING" WHERE "SECURITY_ID" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "SECURITY_ID") = 1) s ON r."SECURITY_ID" = s."SECURITY_ID"
  WHEN MATCHED AND (s."CUSIP" IS DISTINCT FROM r."CUSIP" OR s."ISIN" IS DISTINCT FROM r."ISIN" OR s."SEDOL" IS DISTINCT FROM r."SEDOL" OR s."TICKER" IS DISTINCT FROM r."TICKER" OR s."DESCRIPTION" IS DISTINCT FROM r."DESCRIPTION" OR s."ASSET_CLASS" IS DISTINCT FROM r."ASSET_CLASS" OR s."SECURITY_TYPE" IS DISTINCT FROM r."SECURITY_TYPE" OR s."ISSUER" IS DISTINCT FROM r."ISSUER" OR s."CURRENCY" IS DISTINCT FROM r."CURRENCY" OR s."PRICE_FACTOR" IS DISTINCT FROM r."PRICE_FACTOR" OR s."MATURITY_DATE" IS DISTINCT FROM r."MATURITY_DATE" OR s."STATUS" IS DISTINCT FROM r."STATUS" OR s."SOURCE_UPDATED_AT" IS DISTINCT FROM r."SOURCE_UPDATED_AT") THEN UPDATE SET "CUSIP" = s."CUSIP", "ISIN" = s."ISIN", "SEDOL" = s."SEDOL", "TICKER" = s."TICKER", "DESCRIPTION" = s."DESCRIPTION", "ASSET_CLASS" = s."ASSET_CLASS", "SECURITY_TYPE" = s."SECURITY_TYPE", "ISSUER" = s."ISSUER", "CURRENCY" = s."CURRENCY", "PRICE_FACTOR" = s."PRICE_FACTOR", "MATURITY_DATE" = s."MATURITY_DATE", "STATUS" = s."STATUS", "SOURCE_UPDATED_AT" = s."SOURCE_UPDATED_AT", "REPLICATED_AT" = SYSDATE(), "RUN_ID" = :run_id
  WHEN NOT MATCHED THEN INSERT ("SECURITY_ID", "CUSIP", "ISIN", "SEDOL", "TICKER", "DESCRIPTION", "ASSET_CLASS", "SECURITY_TYPE", "ISSUER", "CURRENCY", "PRICE_FACTOR", "MATURITY_DATE", "STATUS", "SOURCE_UPDATED_AT", "REPLICATED_AT", "RUN_ID") VALUES (s."SECURITY_ID", s."CUSIP", s."ISIN", s."SEDOL", s."TICKER", s."DESCRIPTION", s."ASSET_CLASS", s."SECURITY_TYPE", s."ISSUER", s."CURRENCY", s."PRICE_FACTOR", s."MATURITY_DATE", s."STATUS", s."SOURCE_UPDATED_AT", SYSDATE(), :run_id);
  SELECT COUNT(*) INTO :rows_total FROM {{ DATABASE }}."REFERENCE"."SECURITY_MASTER";
  rows_unchanged := rows_source - rows_conflict - rows_inserted - rows_updated;

  -- 5. The run and its counts.
  INSERT INTO {{ DATABASE }}."CONTROL"."REFERENCE_DATA_RUNS" (RUN_ID, FEED_ID, DOMAIN, STARTED_AT, FINISHED_AT, STATUS, SNAPSHOT_DATE, FILES_LOADED, ROWS_SOURCE, ROWS_CONFLICT, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ROWS_UNCHANGED, ROWS_TOTAL)
  VALUES (:run_id, 'security_master', 'custodial', :started_at, SYSDATE(), 'succeeded', :snapshot, :files_loaded, :rows_source, :rows_conflict, :rows_inserted, :rows_updated, :rows_deleted, :rows_unchanged, :rows_total);
  RETURN 'succeeded: ' || :rows_source || ' source rows, ' || :rows_inserted || ' inserted, ' || :rows_updated || ' updated, ' || :rows_deleted || ' deleted, ' || :rows_conflict || ' in conflict; replica holds ' || :rows_total;
EXCEPTION
  WHEN OTHER THEN
    INSERT INTO {{ DATABASE }}."CONTROL"."REFERENCE_DATA_RUNS" (RUN_ID, FEED_ID, DOMAIN, STARTED_AT, FINISHED_AT, STATUS, SNAPSHOT_DATE, FILES_LOADED, ROWS_SOURCE, ERROR)
    VALUES (:run_id, 'security_master', 'custodial', :started_at, SYSDATE(), 'failed', :snapshot, :files_loaded, :rows_source, :SQLERRM);
    RAISE;
END;
$$;
