-- Account cross-reference (CAS): load the newest snapshot files, compute the delta against the replica,
-- bring the replica in line and record the run with its row counts. Rendered by astra-data reference render.
CREATE OR REPLACE PROCEDURE {{ DATABASE }}."REFERENCE"."REPLICATE_ACCOUNT_XREF"(SNAPSHOT_DATE DATE)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
COMMENT = 'Replicates Account cross-reference from CAS snapshots under account_xref/. Records every run in CONTROL.REFERENCE_DATA_RUNS and every change in ACCOUNT_XREF_CHANGES.'
AS
$$
DECLARE
  run_id STRING DEFAULT UUID_STRING();
  started_at TIMESTAMP_NTZ DEFAULT SYSDATE();
  snapshot DATE DEFAULT COALESCE(:SNAPSHOT_DATE, CURRENT_DATE());
  files_loaded INTEGER DEFAULT 0;
  rows_source INTEGER DEFAULT 0;
  rows_conflict INTEGER DEFAULT 0;
  rows_inserted INTEGER DEFAULT 0;
  rows_updated INTEGER DEFAULT 0;
  rows_deleted INTEGER DEFAULT 0;
  rows_unchanged INTEGER DEFAULT 0;
  rows_total INTEGER DEFAULT 0;
BEGIN
  -- 1. The newest snapshot: files under the feed's folder that no earlier run has loaded.
  TRUNCATE TABLE {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING";
  COPY INTO {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING" ("CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", "ACCOUNT_ID", "FIRM_ID", "ACCOUNT_NAME", "STATUS", "OPENED_ON", "CLOSED_ON", "SOURCE_UPDATED_AT", "SOURCE_FILE", "SOURCE_ROW")
  FROM (SELECT $1::STRING, $2::STRING, $3::STRING, $4::STRING, $5::STRING, $6::STRING, $7::DATE, $8::DATE, $9::TIMESTAMP_NTZ(6), METADATA$FILENAME, METADATA$FILE_ROW_NUMBER FROM @{{ DATABASE }}."REFERENCE"."LANDING"/account_xref/)
  FILE_FORMAT = (FORMAT_NAME = '{{ DATABASE }}.REFERENCE.CSV')
  PATTERN = '.*[.]csv'
  ON_ERROR = 'ABORT_STATEMENT';
  SELECT COUNT(*), COUNT(DISTINCT "SOURCE_FILE") INTO :rows_source, :files_loaded FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING";

  IF (files_loaded = 0) THEN
    INSERT INTO {{ DATABASE }}."CONTROL"."REFERENCE_DATA_RUNS" (RUN_ID, FEED_ID, DOMAIN, STARTED_AT, FINISHED_AT, STATUS, SNAPSHOT_DATE, FILES_LOADED, ROWS_SOURCE, ROWS_TOTAL)
    SELECT :run_id, 'account_xref', 'custodial', :started_at, SYSDATE(), 'skipped', :snapshot, 0, 0, COUNT(*) FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF";
    RETURN 'skipped: no new snapshot files under account_xref/';
  END IF;

  -- 2. Conflicts: keys blank or repeated in the snapshot stay out; the replica keeps what it had.
  INSERT INTO {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_CONFLICTS" (RUN_ID, "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", ROW_COUNT, REJECTION_CODE)
  SELECT :run_id, "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", COUNT(*), 'REFERENCE_DATA_CONFLICT'
  FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING"
  GROUP BY "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER"
  HAVING COUNT(*) > 1 OR NOT ("CUSTODIAN_ID" IS NOT NULL AND "CUSTODIAN_ACCOUNT_NUMBER" IS NOT NULL);
  SELECT COALESCE(SUM(ROW_COUNT), 0) INTO :rows_conflict FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_CONFLICTS" WHERE RUN_ID = :run_id;

  -- 3. The delta: what the snapshot removes, adds and changes.
  INSERT INTO {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_CHANGES" (RUN_ID, CHANGED_AT, CHANGE, "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", BEFORE, AFTER)
  SELECT :run_id, SYSDATE(), 'deleted', r."CUSTODIAN_ID", r."CUSTODIAN_ACCOUNT_NUMBER", OBJECT_CONSTRUCT_KEEP_NULL('CUSTODIAN_ID', r."CUSTODIAN_ID", 'CUSTODIAN_ACCOUNT_NUMBER', r."CUSTODIAN_ACCOUNT_NUMBER", 'ACCOUNT_ID', r."ACCOUNT_ID", 'FIRM_ID', r."FIRM_ID", 'ACCOUNT_NAME', r."ACCOUNT_NAME", 'STATUS', r."STATUS", 'OPENED_ON', r."OPENED_ON", 'CLOSED_ON', r."CLOSED_ON", 'SOURCE_UPDATED_AT', r."SOURCE_UPDATED_AT")::STRING, NULL
  FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF" r
  WHERE NOT EXISTS (SELECT 1 FROM (SELECT "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", "ACCOUNT_ID", "FIRM_ID", "ACCOUNT_NAME", "STATUS", "OPENED_ON", "CLOSED_ON", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING" WHERE "CUSTODIAN_ID" IS NOT NULL AND "CUSTODIAN_ACCOUNT_NUMBER" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER") = 1) s WHERE r."CUSTODIAN_ID" = s."CUSTODIAN_ID" AND r."CUSTODIAN_ACCOUNT_NUMBER" = s."CUSTODIAN_ACCOUNT_NUMBER")
    AND NOT EXISTS (SELECT 1 FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_CONFLICTS" c WHERE c.RUN_ID = :run_id AND c."CUSTODIAN_ID" IS NOT DISTINCT FROM r."CUSTODIAN_ID" AND c."CUSTODIAN_ACCOUNT_NUMBER" IS NOT DISTINCT FROM r."CUSTODIAN_ACCOUNT_NUMBER")
  UNION ALL
  SELECT :run_id, SYSDATE(), 'inserted', s."CUSTODIAN_ID", s."CUSTODIAN_ACCOUNT_NUMBER", NULL, OBJECT_CONSTRUCT_KEEP_NULL('CUSTODIAN_ID', s."CUSTODIAN_ID", 'CUSTODIAN_ACCOUNT_NUMBER', s."CUSTODIAN_ACCOUNT_NUMBER", 'ACCOUNT_ID', s."ACCOUNT_ID", 'FIRM_ID', s."FIRM_ID", 'ACCOUNT_NAME', s."ACCOUNT_NAME", 'STATUS', s."STATUS", 'OPENED_ON', s."OPENED_ON", 'CLOSED_ON', s."CLOSED_ON", 'SOURCE_UPDATED_AT', s."SOURCE_UPDATED_AT")::STRING
  FROM (SELECT "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", "ACCOUNT_ID", "FIRM_ID", "ACCOUNT_NAME", "STATUS", "OPENED_ON", "CLOSED_ON", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING" WHERE "CUSTODIAN_ID" IS NOT NULL AND "CUSTODIAN_ACCOUNT_NUMBER" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER") = 1) s
  WHERE NOT EXISTS (SELECT 1 FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF" r WHERE r."CUSTODIAN_ID" = s."CUSTODIAN_ID" AND r."CUSTODIAN_ACCOUNT_NUMBER" = s."CUSTODIAN_ACCOUNT_NUMBER")
  UNION ALL
  SELECT :run_id, SYSDATE(), 'updated', s."CUSTODIAN_ID", s."CUSTODIAN_ACCOUNT_NUMBER", OBJECT_CONSTRUCT_KEEP_NULL('CUSTODIAN_ID', r."CUSTODIAN_ID", 'CUSTODIAN_ACCOUNT_NUMBER', r."CUSTODIAN_ACCOUNT_NUMBER", 'ACCOUNT_ID', r."ACCOUNT_ID", 'FIRM_ID', r."FIRM_ID", 'ACCOUNT_NAME', r."ACCOUNT_NAME", 'STATUS', r."STATUS", 'OPENED_ON', r."OPENED_ON", 'CLOSED_ON', r."CLOSED_ON", 'SOURCE_UPDATED_AT', r."SOURCE_UPDATED_AT")::STRING, OBJECT_CONSTRUCT_KEEP_NULL('CUSTODIAN_ID', s."CUSTODIAN_ID", 'CUSTODIAN_ACCOUNT_NUMBER', s."CUSTODIAN_ACCOUNT_NUMBER", 'ACCOUNT_ID', s."ACCOUNT_ID", 'FIRM_ID', s."FIRM_ID", 'ACCOUNT_NAME', s."ACCOUNT_NAME", 'STATUS', s."STATUS", 'OPENED_ON', s."OPENED_ON", 'CLOSED_ON', s."CLOSED_ON", 'SOURCE_UPDATED_AT', s."SOURCE_UPDATED_AT")::STRING
  FROM (SELECT "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", "ACCOUNT_ID", "FIRM_ID", "ACCOUNT_NAME", "STATUS", "OPENED_ON", "CLOSED_ON", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING" WHERE "CUSTODIAN_ID" IS NOT NULL AND "CUSTODIAN_ACCOUNT_NUMBER" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER") = 1) s
  JOIN {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF" r ON r."CUSTODIAN_ID" = s."CUSTODIAN_ID" AND r."CUSTODIAN_ACCOUNT_NUMBER" = s."CUSTODIAN_ACCOUNT_NUMBER"
  WHERE s."ACCOUNT_ID" IS DISTINCT FROM r."ACCOUNT_ID" OR s."FIRM_ID" IS DISTINCT FROM r."FIRM_ID" OR s."ACCOUNT_NAME" IS DISTINCT FROM r."ACCOUNT_NAME" OR s."STATUS" IS DISTINCT FROM r."STATUS" OR s."OPENED_ON" IS DISTINCT FROM r."OPENED_ON" OR s."CLOSED_ON" IS DISTINCT FROM r."CLOSED_ON" OR s."SOURCE_UPDATED_AT" IS DISTINCT FROM r."SOURCE_UPDATED_AT";
  SELECT COUNT_IF(CHANGE = 'inserted'), COUNT_IF(CHANGE = 'updated'), COUNT_IF(CHANGE = 'deleted')
    INTO :rows_inserted, :rows_updated, :rows_deleted
  FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_CHANGES" WHERE RUN_ID = :run_id;

  -- 4. Bring the replica in line.
  DELETE FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF" r
  WHERE EXISTS (SELECT 1 FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_CHANGES" c WHERE c.RUN_ID = :run_id AND c.CHANGE = 'deleted' AND c."CUSTODIAN_ID" = r."CUSTODIAN_ID" AND c."CUSTODIAN_ACCOUNT_NUMBER" = r."CUSTODIAN_ACCOUNT_NUMBER");
  MERGE INTO {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF" r
  USING (SELECT "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", "ACCOUNT_ID", "FIRM_ID", "ACCOUNT_NAME", "STATUS", "OPENED_ON", "CLOSED_ON", "SOURCE_UPDATED_AT" FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF_STAGING" WHERE "CUSTODIAN_ID" IS NOT NULL AND "CUSTODIAN_ACCOUNT_NUMBER" IS NOT NULL QUALIFY COUNT(*) OVER (PARTITION BY "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER") = 1) s ON r."CUSTODIAN_ID" = s."CUSTODIAN_ID" AND r."CUSTODIAN_ACCOUNT_NUMBER" = s."CUSTODIAN_ACCOUNT_NUMBER"
  WHEN MATCHED AND (s."ACCOUNT_ID" IS DISTINCT FROM r."ACCOUNT_ID" OR s."FIRM_ID" IS DISTINCT FROM r."FIRM_ID" OR s."ACCOUNT_NAME" IS DISTINCT FROM r."ACCOUNT_NAME" OR s."STATUS" IS DISTINCT FROM r."STATUS" OR s."OPENED_ON" IS DISTINCT FROM r."OPENED_ON" OR s."CLOSED_ON" IS DISTINCT FROM r."CLOSED_ON" OR s."SOURCE_UPDATED_AT" IS DISTINCT FROM r."SOURCE_UPDATED_AT") THEN UPDATE SET "ACCOUNT_ID" = s."ACCOUNT_ID", "FIRM_ID" = s."FIRM_ID", "ACCOUNT_NAME" = s."ACCOUNT_NAME", "STATUS" = s."STATUS", "OPENED_ON" = s."OPENED_ON", "CLOSED_ON" = s."CLOSED_ON", "SOURCE_UPDATED_AT" = s."SOURCE_UPDATED_AT", "REPLICATED_AT" = SYSDATE(), "RUN_ID" = :run_id
  WHEN NOT MATCHED THEN INSERT ("CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", "ACCOUNT_ID", "FIRM_ID", "ACCOUNT_NAME", "STATUS", "OPENED_ON", "CLOSED_ON", "SOURCE_UPDATED_AT", "REPLICATED_AT", "RUN_ID") VALUES (s."CUSTODIAN_ID", s."CUSTODIAN_ACCOUNT_NUMBER", s."ACCOUNT_ID", s."FIRM_ID", s."ACCOUNT_NAME", s."STATUS", s."OPENED_ON", s."CLOSED_ON", s."SOURCE_UPDATED_AT", SYSDATE(), :run_id);
  SELECT COUNT(*) INTO :rows_total FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF";
  rows_unchanged := rows_source - rows_conflict - rows_inserted - rows_updated;

  -- 5. The run and its counts.
  INSERT INTO {{ DATABASE }}."CONTROL"."REFERENCE_DATA_RUNS" (RUN_ID, FEED_ID, DOMAIN, STARTED_AT, FINISHED_AT, STATUS, SNAPSHOT_DATE, FILES_LOADED, ROWS_SOURCE, ROWS_CONFLICT, ROWS_INSERTED, ROWS_UPDATED, ROWS_DELETED, ROWS_UNCHANGED, ROWS_TOTAL)
  VALUES (:run_id, 'account_xref', 'custodial', :started_at, SYSDATE(), 'succeeded', :snapshot, :files_loaded, :rows_source, :rows_conflict, :rows_inserted, :rows_updated, :rows_deleted, :rows_unchanged, :rows_total);
  RETURN 'succeeded: ' || :rows_source || ' source rows, ' || :rows_inserted || ' inserted, ' || :rows_updated || ' updated, ' || :rows_deleted || ' deleted, ' || :rows_conflict || ' in conflict; replica holds ' || :rows_total;
EXCEPTION
  WHEN OTHER THEN
    INSERT INTO {{ DATABASE }}."CONTROL"."REFERENCE_DATA_RUNS" (RUN_ID, FEED_ID, DOMAIN, STARTED_AT, FINISHED_AT, STATUS, SNAPSHOT_DATE, FILES_LOADED, ROWS_SOURCE, ERROR)
    VALUES (:run_id, 'account_xref', 'custodial', :started_at, SYSDATE(), 'failed', :snapshot, :files_loaded, :rows_source, :SQLERRM);
    RAISE;
END;
$$;
