-- One serverless task per feed on its schedule. Task failures are alerted by CONTROL.DETECT_TASK_FAILURES;
-- a feed with no successful run within its expected interval by CONTROL.DETECT_STALE_REFERENCE_DATA.

CREATE OR REPLACE TASK {{ DATABASE }}."REFERENCE"."REFERENCE_SECURITY_MASTER_REPLICATE"
  SCHEDULE = 'USING CRON 0 2 * * * America/New_York'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  SUSPEND_TASK_AFTER_NUM_FAILURES = 10
  COMMENT = 'Replicates Security master (SOS) every day at 0 2 * * * America/New_York; expected at least every 26 hours.'
AS
  CALL {{ DATABASE }}."REFERENCE"."REPLICATE_SECURITY_MASTER"(NULL);
ALTER TASK {{ DATABASE }}."REFERENCE"."REFERENCE_SECURITY_MASTER_REPLICATE" RESUME;

CREATE OR REPLACE TASK {{ DATABASE }}."REFERENCE"."REFERENCE_ACCOUNT_XREF_REPLICATE"
  SCHEDULE = 'USING CRON 30 2 * * * America/New_York'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  SUSPEND_TASK_AFTER_NUM_FAILURES = 10
  COMMENT = 'Replicates Account cross-reference (CAS) every day at 30 2 * * * America/New_York; expected at least every 26 hours.'
AS
  CALL {{ DATABASE }}."REFERENCE"."REPLICATE_ACCOUNT_XREF"(NULL);
ALTER TASK {{ DATABASE }}."REFERENCE"."REFERENCE_ACCOUNT_XREF_REPLICATE" RESUME;
