"""Parity report: match rate, difference groups and trend over a dual-run cycle window, exported as release evidence (S4.2.2, ADR 0034).

A dual-run cycle is one business date's parity comparison (S4.2.1): the
legacy path and the factory ran side by side, and the golden dataset and
the lakehouse both hold that date's rows. `astra-verify parity report`
runs the engine over every already-captured cycle in a window (or all of
them), and aggregates the results into one readable report: the overall
match rate against the product spec's target, every difference grouped
by field across the window, and the trend from the first cycle in the
window to the last. The report is exported into the release evidence of
every source the custodian's capture file names, `releases/<source>
-parity/report.md` and `report.json`, alongside the pack a gate decision
is made from — not generated by `astra-data render`, so a later render
never deletes it (ADR 0018's write_bundle removes files it no longer
produces; a parity report is not one of its outputs).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from astra_data.bundle import Executor

from astra_verification.golden import Capture, ObjectStore, load_index
from astra_verification.parity import MATCH_RATE_TARGET, ParityError, ParityMapping, ParityResult, compare_rows, load_lakehouse_rows, load_legacy_rows

TREND_EPSILON = 0.0005  # smaller swings than this are reported as flat, not noise dressed up as a trend


def captured_business_dates(golden_dir: Path, custodian: str, start: date | None = None, end: date | None = None) -> list[dict]:
    """Every business date already captured for the custodian, latest version of each, within [start, end] when given."""
    index = load_index(golden_dir, custodian)
    latest_by_date: dict[str, dict] = {}
    for entry in index["datasets"]:
        latest_by_date[entry["business_date"]] = entry
    dates = sorted(latest_by_date)
    if start is not None:
        dates = [d for d in dates if d >= start.isoformat()]
    if end is not None:
        dates = [d for d in dates if d <= end.isoformat()]
    if not dates:
        window = f" between {start} and {end}" if start or end else ""
        raise ParityError(f"no golden datasets captured for {custodian}{window}; run astra-verify golden capture first")
    return [latest_by_date[d] for d in dates]


# -- aggregation, pure ---------------------------------------------------------


@dataclass(frozen=True)
class Cycle:
    business_date: str
    result: ParityResult

    def to_dict(self) -> dict:
        return {"business_date": self.business_date, **self.result.to_dict()}


@dataclass
class ParityReport:
    custodian: str
    legacy_output: str
    table: str
    cycles: list[Cycle] = field(default_factory=list)  # ordered oldest to newest

    @property
    def legacy_rows(self) -> int:
        return sum(c.result.legacy_rows for c in self.cycles)

    @property
    def lakehouse_rows(self) -> int:
        return sum(c.result.lakehouse_rows for c in self.cycles)

    @property
    def matched(self) -> int:
        return sum(c.result.matched for c in self.cycles)

    @property
    def match_rate(self) -> float:
        """The window's overall rate, matched rows over legacy rows across every cycle; perfect when there was nothing to compare."""
        if self.legacy_rows == 0:
            return 1.0 if self.lakehouse_rows == 0 else 0.0
        return self.matched / self.legacy_rows

    @property
    def meets_target(self) -> bool:
        return self.match_rate >= MATCH_RATE_TARGET

    @property
    def field_summary(self) -> dict[str, int]:
        """Rows mismatching on each field, summed across every cycle in the window."""
        counts: dict[str, int] = {}
        for cycle in self.cycles:
            for name, count in cycle.result.field_summary.items():
                counts[name] = counts.get(name, 0) + count
        return counts

    @property
    def trend(self) -> str:
        if len(self.cycles) < 2:
            return "n/a: one cycle"
        first, last = self.cycles[0].result.match_rate, self.cycles[-1].result.match_rate
        if last > first + TREND_EPSILON:
            return "improving"
        if last < first - TREND_EPSILON:
            return "declining"
        return "flat"

    def to_dict(self) -> dict:
        return {
            "custodian": self.custodian,
            "legacy_output": self.legacy_output,
            "table": self.table,
            "cycles": len(self.cycles),
            "first_business_date": self.cycles[0].business_date if self.cycles else None,
            "last_business_date": self.cycles[-1].business_date if self.cycles else None,
            "legacy_rows": self.legacy_rows,
            "lakehouse_rows": self.lakehouse_rows,
            "matched": self.matched,
            "match_rate": round(self.match_rate, 6),
            "meets_target": self.meets_target,
            "target": MATCH_RATE_TARGET,
            "trend": self.trend,
            "field_summary": self.field_summary,
            "by_cycle": [c.to_dict() for c in self.cycles],
        }


def aggregate(custodian: str, legacy_output: str, table: str, cycles: list[Cycle]) -> ParityReport:
    return ParityReport(custodian, legacy_output, table, sorted(cycles, key=lambda c: c.business_date))


# -- running the cycles --------------------------------------------------------


def run_cycles(mapping: ParityMapping, golden_dir: Path, store: ObjectStore, executor: Executor, database: str, dates: list[date]) -> list[Cycle]:
    cycles: list[Cycle] = []
    for business_date in dates:
        legacy_rows = load_legacy_rows(golden_dir, store, mapping.custodian, business_date, mapping.legacy_output)
        lakehouse_rows = load_lakehouse_rows(executor, mapping, database, business_date)
        cycles.append(Cycle(business_date.isoformat(), compare_rows(mapping, legacy_rows, lakehouse_rows, business_date)))
    return cycles


# -- the report and its export --------------------------------------------------


def render_markdown(report: ParityReport) -> str:
    out = [f"# Parity report: {report.custodian}", ""]
    out.append(f"Legacy `{report.legacy_output}` vs lakehouse `{report.table}`. {len(report.cycles)} cycle(s)" + (f", {report.cycles[0].business_date} to {report.cycles[-1].business_date}." if report.cycles else "."))
    out.append("")
    out.append(f"**Overall match rate: {report.match_rate:.4%}** (target {MATCH_RATE_TARGET:.1%}) — {'meets target' if report.meets_target else 'below target'}. Trend: {report.trend}.")
    out.append("")
    out.append(f"{report.legacy_rows} legacy row(s), {report.lakehouse_rows} lakehouse row(s), {report.matched} matched, across the window.")
    out.append("")
    out.append("## Trend over cycles")
    out.append("")
    out.append("| Business date | Legacy rows | Lakehouse rows | Matched | Match rate | Missing | Extra | Mismatched |")
    out.append("|---|---|---|---|---|---|---|---|")
    for c in report.cycles:
        r = c.result
        out.append(f"| {c.business_date} | {r.legacy_rows} | {r.lakehouse_rows} | {r.matched} | {r.match_rate:.4%} | {len(r.missing)} | {len(r.extra)} | {len(r.mismatches)} |")
    out.append("")
    out.append("## Difference groups")
    out.append("")
    if report.field_summary:
        out.append("| Field | Rows mismatching (window total) |")
        out.append("|---|---|")
        for name, count in sorted(report.field_summary.items(), key=lambda kv: -kv[1]):
            out.append(f"| `{name}` | {count} |")
    else:
        out.append("No field mismatched in this window.")
    out.append("")
    total_missing = sum(len(c.result.missing) for c in report.cycles)
    total_extra = sum(len(c.result.extra) for c in report.cycles)
    out.append(f"Missing across the window: {total_missing}. Extra: {total_extra}.")
    out.append("")
    return "\n".join(out)


def write_report(report: ParityReport, out: Path) -> tuple[Path, Path]:
    out.mkdir(parents=True, exist_ok=True)
    markdown = out / "report.md"
    data = out / "report.json"
    markdown.write_text(render_markdown(report), encoding="utf-8", newline="\n")
    data.write_text(json.dumps(report.to_dict(), indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8", newline="\n")
    return markdown, data


def bundle_name(source: str) -> str:
    return f"{source.replace('_', '-')}-parity"


def export_to_releases(report: ParityReport, capture: Capture, releases_dir: Path) -> list[Path]:
    """Write the report into the release evidence of every source the capture names: releases/<source>-parity/report.{md,json}."""
    written: list[Path] = []
    for source in capture.sources:
        bundle_dir = Path(releases_dir) / bundle_name(source)
        markdown, data = write_report(report, bundle_dir)
        written.extend([markdown, data])
    return written


def run(
    mapping: ParityMapping,
    capture: Capture,
    golden_dir: Path,
    store: ObjectStore,
    executor: Executor,
    database: str,
    *,
    start: date | None = None,
    end: date | None = None,
    out: Path,
    export: bool = True,
    releases_dir: Path | None = None,
) -> tuple[ParityReport, list[Path]]:
    """Run every already-captured cycle in the window, aggregate, write the working report, and export it into release evidence."""
    dates = [date.fromisoformat(e["business_date"]) for e in captured_business_dates(golden_dir, mapping.custodian, start, end)]
    cycles = run_cycles(mapping, golden_dir, store, executor, database, dates)
    report = aggregate(mapping.custodian, mapping.legacy_output, mapping.table, cycles)
    write_report(report, Path(out))
    exported = export_to_releases(report, capture, releases_dir or Path("releases")) if export else []
    return report, exported
