-- Exception: REJECTION_CODE must be a value of CONTROL.REJECTION_CODES.CODE. Returns rows whose value is not.
SELECT e."EXCEPTION_ID", e."REJECTION_CODE"
FROM {{ DATABASE }}."SILVER"."EXCEPTION" AS e
LEFT JOIN {{ DATABASE }}."CONTROL"."REJECTION_CODES" AS r ON r."CODE" = e."REJECTION_CODE"
WHERE r."CODE" IS NULL;
