-- Lot: the key (CUSTODIAN_ID, ACCOUNT_NUMBER, SECURITY_ID, LOT_ID, AS_OF_DATE) identifies one row. Returns keys with more than one row.
SELECT "CUSTODIAN_ID", "ACCOUNT_NUMBER", "SECURITY_ID", "LOT_ID", "AS_OF_DATE", COUNT(*) AS ROW_COUNT
FROM {{ DATABASE }}."SILVER"."LOT"
GROUP BY "CUSTODIAN_ID", "ACCOUNT_NUMBER", "SECURITY_ID", "LOT_ID", "AS_OF_DATE"
HAVING COUNT(*) > 1;
