-- Position -> Account: (CUSTODIAN_ID, ACCOUNT_NUMBER) must exist in ACCOUNT. Returns rows with no match.
SELECT e."CUSTODIAN_ID", e."ACCOUNT_NUMBER", e."SECURITY_ID", e."AS_OF_DATE"
FROM {{ DATABASE }}."SILVER"."POSITION" AS e
LEFT JOIN {{ DATABASE }}."SILVER"."ACCOUNT" AS r ON r."CUSTODIAN_ID" = e."CUSTODIAN_ID" AND r."ACCOUNT_NUMBER" = e."ACCOUNT_NUMBER"
WHERE r."CUSTODIAN_ID" IS NULL;
