-- Transaction -> Account: (CUSTODIAN_ID, ACCOUNT_NUMBER) must exist in ACCOUNT. Returns rows with no match.
SELECT e."CUSTODIAN_ID", e."TRANSACTION_ID", e."ACCOUNT_NUMBER"
FROM {{ DATABASE }}."SILVER"."TRANSACTION" AS e
LEFT JOIN {{ DATABASE }}."SILVER"."ACCOUNT" AS r ON r."CUSTODIAN_ID" = e."CUSTODIAN_ID" AND r."ACCOUNT_NUMBER" = e."ACCOUNT_NUMBER"
WHERE r."CUSTODIAN_ID" IS NULL;
