-- Account cross-reference: the key (CUSTODIAN_ID, CUSTODIAN_ACCOUNT_NUMBER) identifies one replica row. Returns keys with more than one.
SELECT "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER", COUNT(*) AS ROW_COUNT
FROM {{ DATABASE }}."REFERENCE"."ACCOUNT_XREF"
GROUP BY "CUSTODIAN_ID", "CUSTODIAN_ACCOUNT_NUMBER"
HAVING COUNT(*) > 1;
